#161214 Jennifer Briner
#Discriminability modeling: a script for calculating the discriminability of different yellows (Eueides vs. Heliconius) 
#-------------------------------------------------

#Goal: for each visual system, get the percentage of pairwise pigment comparisons (Eueides vs. Heliconius yellow) that are greater than 1 JND

#Inputs: spreadsheet of with spectra for different yellows (2 categories), visual system spreadsheets generated by SPEC from Kyle's electrophysiology experiments.

  #Visual systems used
    #H. erato female: UV1, UV2, B, L
    #H. erato male: UV2, B, L
    #H. erato male hypothetical: UV1, B, L (models a hypothetical, ancestral male eye expressing only UV1 rather than the derived UV2)
    #H. melpomene (sexually monomorphic)
    #H. ismenius (sexually monomorphic)




#----------------------
#Preliminaries 
#----------------------


rm(list = ls())
library(DT)
library(gsubfn)


#Read in data 

  setwd("/home/jbriner/Dropbox/School/UCI/Briscoe/Experiments/DiscriminabilityModeling/YellowCompare_HeliconiusEueides/InputFiles")
  
  #pigment signals
    yellows.df <- read.delim("H_erato_HDYellow_E_FDY_clean.csv", header=TRUE, sep = ",", row.names=1) 
    
  #visual systems (processed data from SPEC [options selected: account for VK and irradiance])
    herato_f_Kyle.df <- read.delim("R_161206_Herato_female_Kyle.csv", header=TRUE, sep = ",", row.names=1)
    herato_m_Kyle.df <- read.delim("R_161206_Herato_male_Kyle.csv", header=TRUE, sep = ",", row.names=1)
    herato_h_Kyle.df <- read.delim("R_161214_Herato_hypotheticalM_Kyle.csv", header=TRUE, sep = ",", row.names=1) #hypothetical H. erato male
    hmelpomene_f_Kyle.df <- read.delim("R_161206_Hmelpomene_female_Kyle.csv", header=TRUE, sep = ",", row.names=1)
    hmelpomene_m_Kyle.df <- read.delim("R_161206_Hmelpomene_male_Kyle.csv", header=TRUE, sep = ",", row.names=1)
    hismenius_f_Kyle.df <- read.delim("R_161206_Hismenius_female_Kyle.csv", header=TRUE, sep = ",", row.names=1)
    hismenius_m_Kyle.df <- read.delim("R_161206_Hismenius_male_Kyle.csv", header=TRUE, sep = ",", row.names=1)


          #manually modify this name each time - this string feeds into write.csv
            visualsystem <- "HeratoFKyle"  
          #manually set the visual system to test
            visualsystem.df <-herato_f_Kyle.df

            
            
#----------------------------- 

 #Plot (optional) - Get a sense for yellows.df
            
    library(ggplot2)
    library(reshape)
  
  yellows_wavecol.df <- read.delim("H_erato_HDYellow_E_FDY_clean.csv", header=TRUE, sep = ",")  
  yellows.df.melted <- melt(yellows_wavecol.df, id = "Wavelength") #creates a new data frame with 3 columns: x (the axis - wavelength), variable (the pigment), and value
    
  yellows.plot <-ggplot(data = yellows.df.melted, aes(x = Wavelength, y = value, color = variable)) +
      geom_line() + 
      ggtitle("Spectra of different yellows: Heliconius vs. Eueides pigments") +
      labs(x="Wavelength (nm)", y="Reflectance (%)") +
      theme(plot.title = element_text(family = "Trebuchet MS", color="#000066", face="bold", size=24)) +
      theme(axis.title = element_text(family = "Trebuchet MS", color="#666666", face="bold", size=16)) 
  
  yellows.plot
   
  
  
#------------------------------    
    
#Yellows data: handling the yellows data (physical stimuli) to generate a massive pairwise data frame of differences
  
  
  #Subset the yellow data into categories: Heliconius yellow, Eueides yellow.
    yellows_heliconius.df <- yellows.df[ , grepl( "HER" , names(yellows.df) ) ]  #only pulls out columns containing string "HER"
    yellows_eueides.df <- yellows.df[ , grepl( "EEA|EIS|ESU|ETH", names(yellows.df) ) ]  #only pulls out columns containing strings EEA, EIS, ESU, or ETH

  
#Pairwise difference ratios for yellows - compare each column by every other for the degree of difference in each cell
  
  #Compare all the columns pairwise by type - all Heliconius pigments against all Eueides pigments. Find the relative difference for each.
    #The output is a data frame where every column is a difference ratio of one HER spectrum vs. one EUE spectrum. 
    #Each pairwise comparison occurs twice because both pigments get a column where they are treated as the original stimulus value (the divisor).
  #JND calculation: (absolute difference btwn stimuli compared / initial stimulus intensity)
 
    
      HERpairwise.df <-as.data.frame(lapply(1:14, function(x){
        temp <-(abs(yellows_heliconius.df[,x] - yellows_eueides.df[,1:ncol(yellows_eueides.df)]) / yellows_heliconius.df[,x] )
      })) #looped over number of columns in yellows_heliconius.df (14)
      
      EUEpairwise.df <-as.data.frame(lapply(1:11, function(x){
        temp <-(abs(yellows_eueides.df[,x] - yellows_heliconius.df[,1:ncol(yellows_heliconius.df)]) / yellows_eueides.df[,x] )
      })) #looped over number of columns in yellows_eueides.df (11)
      
        yellows_relativedifferences.df <-as.data.frame( c(HERpairwise.df, EUEpairwise.df) ) #combine into one data frame
            rownames(yellows_relativedifferences.df) <- yellows_wavecol.df$Wavelength #add row names back on
            
          #save yellows_pairwise.df to file (remove # to reactivate)
            #write.table(yellows_relativedifferences.df, "/home/jbriner/Dropbox/School/UCI/Briscoe/Experiments/DiscriminabilityModeling/YellowCompare_HeliconiusEueides/OutputFiles/yellowspairwiseratios.csv")
        
                
            
#------------------------------   

#NEEDS WORK
        
#Now run the visual systems data through the "yellows relative differences" data frame 
    
    # At each wavelength, the relative difference between the pigments compared needs to be at least as large as 
    # the visual system's JND value for the pigments to be discriminated.

     #For each column (pigment pair), what's the max? For what region of the spectra is the difference ratio greatest?
            
            visualsystem.df
            yellows_relativedifferences.df 
  


  
#Save output to csv 
#------------------------------
  
  date = Sys.Date()
    #write output to csv
      write.csv(x=yellowcompare.df, file=paste("YellowCompare", visualsystem, sep="_", date))


    